version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - node-network
    working_dir: /app  # Adicionado o diretório de trabalho

  nginx:
    image: nginx
    container_name: node-nginx
    volumes:
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
    ports:
      - "8080:80"
    networks:
      - node-network

  postgres:
    image: postgres
    container_name: node-postgres
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    networks:
      - node-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: node-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    networks:
      - node-network

networks:
  node-network:
